#
# Installs a WebSphere Application Server offering. Requires Installation Manager to be installed on the target machine.
# You can use the ibmim module to install Installation Manager.
#

- hosts: localhost
  connection: local
  tasks:
    - name: Download installer zip
      get_url:
        url: http://masp-repo.volvocars.biz/~ibmrepo/im/linux/agent.installer.linux.x86_64-latest.zip
        dest: /tmp/

    - name: Create IM directory
      file:
        state: directory
        path: /tmp/im

    - name: Unarchive installer zip
      unarchive:
        src: /tmp/agent.installer.linux.x86_64-latest.zip
        dest: /tmp/im/

    - name: Install Installation Manager
      ibmim:
        src: /tmp/im/